# Generated by Django 5.2.5 on 2025-08-20 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Optional description of the expense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vehicle.expensecategory')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Expense',
                'verbose_name_plural': 'Vehicle Expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='vehicle_veh_date_99962a_idx'), models.Index(fields=['vehicle', 'date'], name='vehicle_veh_vehicle_87b1d7_idx'), models.Index(fields=['category', 'date'], name='vehicle_veh_categor_63a6bc_idx')],
            },
        ),
    ]
