# Generated by Django 5.2.5 on 2025-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_expensecategory_vehicleexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='emoji',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
