# Generated by Django 5.2.5 on 2025-08-16 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', help_text='The name of the website displayed to users', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Address of the organization')),
                ('phone1', models.CharField(default='0000000000', help_text='Primary contact number', max_length=10, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain only digits', regex='^\\d+$')])),
                ('phone2', models.CharField(blank=True, default='0000000000', help_text='Secondary contact number', max_length=10, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain only digits', regex='^\\d+$')])),
                ('site_logo', models.ImageField(blank=True, help_text='Site logo image (recommended size: 200x60px)', null=True, upload_to='site_logo/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
