# Generated by Django 5.2.5 on 2025-08-20 15:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Site logo image (recommended size: 200x60px)', null=True, upload_to=core.models.SiteConfiguration._get_site_logo_path),
        ),
    ]
