# Generated by Django 5.2.5 on 2025-08-29 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siteconfiguration_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone1',
            field=models.CharField(default='0000000000', help_text='Primary contact number', max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be exactly 10 digits long.'), django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain only digits', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone2',
            field=models.CharField(blank=True, default='0000000000', help_text='Secondary contact number', max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be exactly 10 digits long.'), django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain only digits', regex='^\\d+$')]),
        ),
    ]
