# Generated by Django 5.2.5 on 2025-08-29 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numeric.', regex='^\\d+$'), django.core.validators.MinLengthValidator(10, message='Phone number must be exactly 10 digits long.')]),
        ),
    ]
